// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'ap-southeast-1:60b2c047-386a-42ab-9814-de67c531f90f',
    'aws_cognito_region': 'ap-southeast-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'isb-hosting-mobilehub-925948942',
    'aws_content_delivery_bucket_region': 'ap-southeast-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd2d8u6bsu80t1g.cloudfront.net',
    'aws_mobile_analytics_app_id': 'c30dc6b028cc4c83871e19e8b8568347',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '90a9996a-3669-11e8-8c0d-47db4ca004cf',
    'aws_project_name': 'ISB-2018-04-02-18-32-26',
    'aws_project_region': 'ap-southeast-1',
    'aws_resource_name_prefix': 'isb-mobilehub-925948942',
}

export default awsmobile;
